name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Apache2
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            rm -rf /var/www/html/project1
            mkdir -p /var/www/html/project1
            cp -r dist/* /var/www/html/project1
