name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Apache2
    runs-on: self-hosted
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd T27-Project-1
            git pull
            npm ci
            npm run build
            rm -rf /var/www/html/project1
            mkdir -p /var/www/html/project1
            cp -r dist/* /var/www/html/project1
